const DEFAULT_CLIENT_VERSION = 'c18.0.0'
const DEFAULT_DEVICE_NAME = 'JavaScript Keeper SDK'
const DEFAULT_CONFIG_DIR = '.keeper'
const DEFAULT_LOG_FORMAT = '!'

export const SdkDefaults = {
    CLIENT_VERSION: DEFAULT_CLIENT_VERSION,
    DEVICE_NAME: DEFAULT_DEVICE_NAME,
    CONFIG_DIR: DEFAULT_CONFIG_DIR,
    LOG_FORMAT: DEFAULT_LOG_FORMAT,
} as const

export const AuthDefaults = {
    MAX_LOGIN_ATTEMPTS: 5,
    APPROVAL_TIMEOUT_MS: 60_000,
    CODE_VALIDATION_DELAY_MS: 2_000,
} as const

export enum AuthErrorCode {
    InvalidCredentials = 'invalid_credentials',
    MissingUsername = 'missing_username',
    MissingPassword = 'missing_password',
    MaxAttemptsExceeded = 'max_attempts_exceeded',
    UserCancelled = 'user_cancelled',
    Unsupported2FAChannel = 'unsupported_2fa_channel',
}

export enum SessionErrorCode {
    NotLoggedIn = 'not_logged_in',
    DeviceNotRegistered = 'device_not_registered',
    NoPreviousLogin = 'no_previous_login',
    NoCloneCode = 'no_clone_code',
    PersistentLoginFailed = 'persistent_login_failed',
    SessionTokenExpired = 'session_token_expired',
    SyncFailed = 'sync_failed',
}

export enum ValidationErrorCode {
    InvalidPattern = 'invalid_pattern',
}

export enum RoleErrorCode {
    RoleRequired = 'role_required',
    RoleNotFound = 'role_not_found',
    MultipleRoleMatches = 'multiple_role_matches',
    NoRolesToAdd = 'no_roles_to_add',
    NoRolesToUpdate = 'no_roles_to_update',
    NoRolesToDelete = 'no_roles_to_delete',
    RoleAddFailed = 'role_add_failed',
    RoleUpdateFailed = 'role_update_failed',
    RoleDeleteFailed = 'role_delete_failed',
    RoleIdAllocationFailed = 'role_id_allocation_failed',
    RoleRenameMultiNotAllowed = 'role_rename_multi_not_allowed',
    RoleNameEmpty = 'role_name_empty',
    RoleEnforcementFailed = 'role_enforcement_failed',
    NoEnforcementsToApply = 'no_enforcements_to_apply',
    RoleSourceRequired = 'role_source_required',
    RoleCopyFailed = 'role_copy_failed',
    NoUsersForRoleOp = 'no_users_for_role_op',
    RoleUserAddFailed = 'role_user_add_failed',
    RoleUserRemoveFailed = 'role_user_remove_failed',
    NoNodesForRoleOp = 'no_nodes_for_role_op',
    RoleManagedNodeAddFailed = 'role_managed_node_add_failed',
    RoleManagedNodeUpdateFailed = 'role_managed_node_update_failed',
    RoleManagedNodeRemoveFailed = 'role_managed_node_remove_failed',
    ManagedNodeNotManagedByRole = 'managed_node_not_managed_by_role',
    NoPrivilegesSpecified = 'no_privileges_specified',
    RolePrivilegeAddFailed = 'role_privilege_add_failed',
    RolePrivilegeRemoveFailed = 'role_privilege_remove_failed',
    RoleKeyUnavailable = 'role_key_unavailable',
}

export enum NsfErrorCode {
    NotFound = 'nsf_not_found',
    MultipleMatches = 'nsf_multiple_matches',
    LegacyRecord = 'nsf_legacy_record',
    LegacyFolder = 'nsf_legacy_folder',
    PermissionDenied = 'nsf_permission_denied',
    LinkFailed = 'nsf_link_failed',
    RemoveFailed = 'nsf_remove_failed',
    FolderRequired = 'nsf_folder_required',
    TooManyRecords = 'nsf_too_many_records',
    TooManyFolders = 'nsf_too_many_folders',
    MissingKey = 'nsf_missing_key',
    MkdirFailed = 'nsf_mkdir_failed',
    UpdateFailed = 'nsf_update_failed',
    DetailsFailed = 'nsf_details_failed',
    AddFailed = 'nsf_add_failed',
    ShareFailed = 'nsf_share_failed',
    ShortcutFailed = 'nsf_shortcut_failed',
    TransferFailed = 'nsf_transfer_failed',
    RecordPermissionFailed = 'nsf_record_permission_failed',
}

export enum TeamErrorCode {
    TeamRequired = 'team_required',
    TeamNotFound = 'team_not_found',
    MultipleTeamMatches = 'multiple_team_matches',
    NoTeamsToAdd = 'no_teams_to_add',
    NoTeamsToUpdate = 'no_teams_to_update',
    NoTeamsToDelete = 'no_teams_to_delete',
    ParentNodeRequired = 'parent_node_required',
    ParentNodeNotFound = 'parent_node_not_found',
    MultipleParentNodeMatches = 'multiple_parent_node_matches',
    EnterprisePublicKeyMissing = 'enterprise_public_key_missing',
    EnterpriseTreeKeyUnavailable = 'enterprise_tree_key_unavailable',
    DataKeyMissing = 'data_key_missing',
    TeamAddFailed = 'team_add_failed',
    TeamUpdateFailed = 'team_update_failed',
    TeamDeleteFailed = 'team_delete_failed',
    MultipleTeamRenameNotAllowed = 'multiple_team_rename_not_allowed',
    QueuedTeamNotFound = 'queued_team_not_found',
    TeamNameTooLong = 'team_name_too_long',
}

export enum NodeErrorCode {
    NoNodesToAdd = 'no_nodes_to_add',
    NoNodesToUpdate = 'no_nodes_to_update',
    NoNodesToDelete = 'no_nodes_to_delete',
    NodeNotFound = 'node_not_found',
    MultipleNodeMatches = 'multiple_node_matches',
    NodeNameEmpty = 'node_name_empty',
    NodeNameTooLong = 'node_name_too_long',
    NodeAddFailed = 'node_add_failed',
    NodeUpdateFailed = 'node_update_failed',
    NodeDeleteFailed = 'node_delete_failed',
    CannotMoveNodeIntoSelf = 'cannot_move_node_into_self',
    CannotDeleteRootNode = 'cannot_delete_root_node',
    MultipleNodeRenameNotAllowed = 'multiple_node_rename_not_allowed',
}

export enum AuditReportErrorCode {
    InvalidReportType = 'audit_invalid_report_type',
    InvalidCreatedFilter = 'audit_invalid_created_filter',
    InvalidFilter = 'audit_invalid_filter',
    InvalidLimit = 'audit_invalid_limit',
    ColumnsRequired = 'audit_columns_required',
    DimensionColumnRequired = 'audit_dimension_column_required',
    DimensionFailed = 'audit_dimension_failed',
    ReportFailed = 'audit_report_failed',
    ReportingNotEnabled = 'audit_reporting_not_enabled',
    LicenseCheckFailed = 'audit_license_check_failed',
}

export enum ActionReportErrorCode {
    ReportFailed = 'action_report_failed',
    InvalidAction = 'action_report_invalid_action',
    TargetUserRequired = 'action_report_target_user_required',
    TransferNotSupported = 'action_report_transfer_not_supported',
    NodeNotFound = 'action_report_node_not_found',
    NodeNotUnique = 'action_report_node_not_unique',
}

export enum PasswordReportErrorCode {
    PolicyRequired = 'password_report_policy_required',
}

export enum PamErrorCode {
    GatewayListFailed = 'pam_gateway_list_failed',
    GatewayCreateFailed = 'pam_gateway_create_failed',
    GatewayNameRequired = 'pam_gateway_name_required',
    KsmAppRequired = 'pam_ksm_app_required',
    KsmAppNotFound = 'pam_ksm_app_not_found',
    MultipleKsmAppMatches = 'pam_multiple_ksm_app_matches',
    InvalidTokenExpiry = 'pam_invalid_token_expiry',
    ConfigInitFailed = 'pam_config_init_failed',
    GatewayRequired = 'pam_gateway_required',
    GatewayNotFound = 'pam_gateway_not_found',
    GatewayEditNothingToDo = 'pam_gateway_edit_nothing_to_do',
    GatewayEditFailed = 'pam_gateway_edit_failed',
    GatewayNodeNotFound = 'pam_gateway_node_not_found',
    MultipleGatewayNodeMatches = 'pam_multiple_gateway_node_matches',
    GatewayRemoveFailed = 'pam_gateway_remove_failed',
    GatewayInvalidMaxInstances = 'pam_gateway_invalid_max_instances',
    GatewaySetMaxInstancesFailed = 'pam_gateway_set_max_instances_failed',
    ConfigNotFound = 'pam_config_not_found',
    ConfigInvalid = 'pam_config_invalid',
    ConfigTitleRequired = 'pam_config_title_required',
    ConfigTypeRequired = 'pam_config_type_required',
    ConfigTypeInvalid = 'pam_config_type_invalid',
    ConfigSharedFolderRequired = 'pam_config_shared_folder_required',
    ConfigSharedFolderNotFound = 'pam_config_shared_folder_not_found',
    ConfigCreateFailed = 'pam_config_create_failed',
    ConfigMoveFailed = 'pam_config_move_failed',
    ConfigRequired = 'pam_config_required',
    ConfigEditNothingToDo = 'pam_config_edit_nothing_to_do',
    ConfigEditFailed = 'pam_config_edit_failed',
    MultipleConfigMatches = 'pam_multiple_config_matches',
    ConfigRemoveFailed = 'pam_config_remove_failed',
}

export enum UserErrorCode {
    NoUsersToUpdate = 'no_users_to_update',
    NoUsersToAdd = 'no_users_to_add',
    NoUsersToDelete = 'no_users_to_delete',
    UserNotFound = 'user_not_found',
    MultipleUserMatches = 'multiple_user_matches',
    UserAddFailed = 'user_add_failed',
    UserUpdateFailed = 'user_update_failed',
    UserDeleteFailed = 'user_delete_failed',
    RoleNotFound = 'role_not_found',
    NoUsersToAction = 'no_users_to_action',
    UserActionFailed = 'user_action_failed',
    UserActionAllNotSupported = 'user_action_all_not_supported',
    UserAliasFailed = 'user_alias_failed',
    NoTeamsForUserOp = 'no_teams_for_user_op',
    TeamUserAddFailed = 'team_user_add_failed',
    TeamUserRemoveFailed = 'team_user_remove_failed',
    TeamEnterpriseUserUpdateFailed = 'team_enterprise_user_update_failed',
    HideSharedFoldersRequired = 'hide_shared_folders_required',
}

export const ResultCodes = {
    INVALID_CREDENTIALS: AuthErrorCode.InvalidCredentials,
    MISSING_USERNAME: AuthErrorCode.MissingUsername,
    MISSING_PASSWORD: AuthErrorCode.MissingPassword,
    MAX_ATTEMPTS_EXCEEDED: AuthErrorCode.MaxAttemptsExceeded,
    USER_CANCELLED: AuthErrorCode.UserCancelled,
    UNSUPPORTED_2FA_CHANNEL: AuthErrorCode.Unsupported2FAChannel,
    NOT_LOGGED_IN: SessionErrorCode.NotLoggedIn,
    DEVICE_NOT_REGISTERED: SessionErrorCode.DeviceNotRegistered,
    NO_PREVIOUS_LOGIN: SessionErrorCode.NoPreviousLogin,
    NO_CLONE_CODE: SessionErrorCode.NoCloneCode,
    PERSISTENT_LOGIN_FAILED: SessionErrorCode.PersistentLoginFailed,
    SESSION_TOKEN_EXPIRED: SessionErrorCode.SessionTokenExpired,
    SYNC_FAILED: SessionErrorCode.SyncFailed,
    INVALID_PATTERN: ValidationErrorCode.InvalidPattern,
    ROLE_REQUIRED: RoleErrorCode.RoleRequired,
    ROLE_NOT_FOUND: RoleErrorCode.RoleNotFound,
    MULTIPLE_ROLE_MATCHES: RoleErrorCode.MultipleRoleMatches,
    NO_ROLES_TO_ADD: RoleErrorCode.NoRolesToAdd,
    NO_ROLES_TO_UPDATE: RoleErrorCode.NoRolesToUpdate,
    NO_ROLES_TO_DELETE: RoleErrorCode.NoRolesToDelete,
    ROLE_ADD_FAILED: RoleErrorCode.RoleAddFailed,
    ROLE_UPDATE_FAILED: RoleErrorCode.RoleUpdateFailed,
    ROLE_DELETE_FAILED: RoleErrorCode.RoleDeleteFailed,
    ROLE_ID_ALLOCATION_FAILED: RoleErrorCode.RoleIdAllocationFailed,
    ROLE_RENAME_MULTI_NOT_ALLOWED: RoleErrorCode.RoleRenameMultiNotAllowed,
    ROLE_NAME_EMPTY: RoleErrorCode.RoleNameEmpty,
    ROLE_ENFORCEMENT_FAILED: RoleErrorCode.RoleEnforcementFailed,
    NO_ENFORCEMENTS_TO_APPLY: RoleErrorCode.NoEnforcementsToApply,
    ROLE_SOURCE_REQUIRED: RoleErrorCode.RoleSourceRequired,
    ROLE_COPY_FAILED: RoleErrorCode.RoleCopyFailed,
    NO_USERS_FOR_ROLE_OP: RoleErrorCode.NoUsersForRoleOp,
    ROLE_USER_ADD_FAILED: RoleErrorCode.RoleUserAddFailed,
    ROLE_USER_REMOVE_FAILED: RoleErrorCode.RoleUserRemoveFailed,
    NO_NODES_FOR_ROLE_OP: RoleErrorCode.NoNodesForRoleOp,
    ROLE_MANAGED_NODE_ADD_FAILED: RoleErrorCode.RoleManagedNodeAddFailed,
    ROLE_MANAGED_NODE_UPDATE_FAILED: RoleErrorCode.RoleManagedNodeUpdateFailed,
    ROLE_MANAGED_NODE_REMOVE_FAILED: RoleErrorCode.RoleManagedNodeRemoveFailed,
    MANAGED_NODE_NOT_MANAGED_BY_ROLE: RoleErrorCode.ManagedNodeNotManagedByRole,
    NO_PRIVILEGES_SPECIFIED: RoleErrorCode.NoPrivilegesSpecified,
    ROLE_PRIVILEGE_ADD_FAILED: RoleErrorCode.RolePrivilegeAddFailed,
    ROLE_PRIVILEGE_REMOVE_FAILED: RoleErrorCode.RolePrivilegeRemoveFailed,
    ROLE_KEY_UNAVAILABLE: RoleErrorCode.RoleKeyUnavailable,
    NSF_NOT_FOUND: NsfErrorCode.NotFound,
    MULTIPLE_NSF_MATCHES: NsfErrorCode.MultipleMatches,
    NSF_LEGACY_RECORD: NsfErrorCode.LegacyRecord,
    NSF_LEGACY_FOLDER: NsfErrorCode.LegacyFolder,
    NSF_PERMISSION_DENIED: NsfErrorCode.PermissionDenied,
    NSF_LINK_FAILED: NsfErrorCode.LinkFailed,
    NSF_REMOVE_FAILED: NsfErrorCode.RemoveFailed,
    NSF_FOLDER_REQUIRED: NsfErrorCode.FolderRequired,
    NSF_TOO_MANY_RECORDS: NsfErrorCode.TooManyRecords,
    NSF_TOO_MANY_FOLDERS: NsfErrorCode.TooManyFolders,
    NSF_MISSING_KEY: NsfErrorCode.MissingKey,
    NSF_MKDIR_FAILED: NsfErrorCode.MkdirFailed,
    NSF_UPDATE_FAILED: NsfErrorCode.UpdateFailed,
    NSF_DETAILS_FAILED: NsfErrorCode.DetailsFailed,
    NSF_ADD_FAILED: NsfErrorCode.AddFailed,
    NSF_SHARE_FAILED: NsfErrorCode.ShareFailed,
    NSF_SHORTCUT_FAILED: NsfErrorCode.ShortcutFailed,
    NSF_TRANSFER_FAILED: NsfErrorCode.TransferFailed,
    NSF_RECORD_PERMISSION_FAILED: NsfErrorCode.RecordPermissionFailed,
    TEAM_REQUIRED: TeamErrorCode.TeamRequired,
    TEAM_NOT_FOUND: TeamErrorCode.TeamNotFound,
    MULTIPLE_TEAM_MATCHES: TeamErrorCode.MultipleTeamMatches,
    NO_TEAMS_TO_ADD: TeamErrorCode.NoTeamsToAdd,
    NO_TEAMS_TO_UPDATE: TeamErrorCode.NoTeamsToUpdate,
    NO_TEAMS_TO_DELETE: TeamErrorCode.NoTeamsToDelete,
    PARENT_NODE_REQUIRED: TeamErrorCode.ParentNodeRequired,
    PARENT_NODE_NOT_FOUND: TeamErrorCode.ParentNodeNotFound,
    MULTIPLE_PARENT_NODE_MATCHES: TeamErrorCode.MultipleParentNodeMatches,
    ENTERPRISE_PUBLIC_KEY_MISSING: TeamErrorCode.EnterprisePublicKeyMissing,
    ENTERPRISE_TREE_KEY_UNAVAILABLE: TeamErrorCode.EnterpriseTreeKeyUnavailable,
    DATA_KEY_MISSING: TeamErrorCode.DataKeyMissing,
    TEAM_ADD_FAILED: TeamErrorCode.TeamAddFailed,
    TEAM_UPDATE_FAILED: TeamErrorCode.TeamUpdateFailed,
    TEAM_DELETE_FAILED: TeamErrorCode.TeamDeleteFailed,
    MULTIPLE_TEAM_RENAME_NOT_ALLOWED: TeamErrorCode.MultipleTeamRenameNotAllowed,
    QUEUED_TEAM_NOT_FOUND: TeamErrorCode.QueuedTeamNotFound,
    TEAM_NAME_TOO_LONG: TeamErrorCode.TeamNameTooLong,
    NO_NODES_TO_ADD: NodeErrorCode.NoNodesToAdd,
    NO_NODES_TO_UPDATE: NodeErrorCode.NoNodesToUpdate,
    NO_NODES_TO_DELETE: NodeErrorCode.NoNodesToDelete,
    NODE_NOT_FOUND: NodeErrorCode.NodeNotFound,
    MULTIPLE_NODE_MATCHES: NodeErrorCode.MultipleNodeMatches,
    NODE_NAME_EMPTY: NodeErrorCode.NodeNameEmpty,
    NODE_NAME_TOO_LONG: NodeErrorCode.NodeNameTooLong,
    NODE_ADD_FAILED: NodeErrorCode.NodeAddFailed,
    NODE_UPDATE_FAILED: NodeErrorCode.NodeUpdateFailed,
    NODE_DELETE_FAILED: NodeErrorCode.NodeDeleteFailed,
    CANNOT_MOVE_NODE_INTO_SELF: NodeErrorCode.CannotMoveNodeIntoSelf,
    CANNOT_DELETE_ROOT_NODE: NodeErrorCode.CannotDeleteRootNode,
    MULTIPLE_NODE_RENAME_NOT_ALLOWED: NodeErrorCode.MultipleNodeRenameNotAllowed,
    NO_USERS_TO_UPDATE: UserErrorCode.NoUsersToUpdate,
    NO_USERS_TO_ADD: UserErrorCode.NoUsersToAdd,
    NO_USERS_TO_DELETE: UserErrorCode.NoUsersToDelete,
    USER_NOT_FOUND: UserErrorCode.UserNotFound,
    MULTIPLE_USER_MATCHES: UserErrorCode.MultipleUserMatches,
    USER_ADD_FAILED: UserErrorCode.UserAddFailed,
    USER_UPDATE_FAILED: UserErrorCode.UserUpdateFailed,
    USER_DELETE_FAILED: UserErrorCode.UserDeleteFailed,
    NO_USERS_TO_ACTION: UserErrorCode.NoUsersToAction,
    USER_ACTION_FAILED: UserErrorCode.UserActionFailed,
    USER_ACTION_ALL_NOT_SUPPORTED: UserErrorCode.UserActionAllNotSupported,
    USER_ALIAS_FAILED: UserErrorCode.UserAliasFailed,
    NO_TEAMS_FOR_USER_OP: UserErrorCode.NoTeamsForUserOp,
    TEAM_USER_ADD_FAILED: UserErrorCode.TeamUserAddFailed,
    TEAM_USER_REMOVE_FAILED: UserErrorCode.TeamUserRemoveFailed,
    TEAM_ENTERPRISE_USER_UPDATE_FAILED: UserErrorCode.TeamEnterpriseUserUpdateFailed,
    HIDE_SHARED_FOLDERS_REQUIRED: UserErrorCode.HideSharedFoldersRequired,
    AUDIT_INVALID_REPORT_TYPE: AuditReportErrorCode.InvalidReportType,
    AUDIT_INVALID_CREATED_FILTER: AuditReportErrorCode.InvalidCreatedFilter,
    AUDIT_INVALID_FILTER: AuditReportErrorCode.InvalidFilter,
    AUDIT_INVALID_LIMIT: AuditReportErrorCode.InvalidLimit,
    AUDIT_COLUMNS_REQUIRED: AuditReportErrorCode.ColumnsRequired,
    AUDIT_DIMENSION_COLUMN_REQUIRED: AuditReportErrorCode.DimensionColumnRequired,
    AUDIT_DIMENSION_FAILED: AuditReportErrorCode.DimensionFailed,
    AUDIT_REPORT_FAILED: AuditReportErrorCode.ReportFailed,
    AUDIT_REPORTING_NOT_ENABLED: AuditReportErrorCode.ReportingNotEnabled,
    AUDIT_LICENSE_CHECK_FAILED: AuditReportErrorCode.LicenseCheckFailed,
    ACTION_REPORT_FAILED: ActionReportErrorCode.ReportFailed,
    ACTION_REPORT_INVALID_ACTION: ActionReportErrorCode.InvalidAction,
    ACTION_REPORT_TARGET_USER_REQUIRED: ActionReportErrorCode.TargetUserRequired,
    ACTION_REPORT_TRANSFER_NOT_SUPPORTED: ActionReportErrorCode.TransferNotSupported,
    ACTION_REPORT_NODE_NOT_FOUND: ActionReportErrorCode.NodeNotFound,
    ACTION_REPORT_NODE_NOT_UNIQUE: ActionReportErrorCode.NodeNotUnique,
    PASSWORD_REPORT_POLICY_REQUIRED: PasswordReportErrorCode.PolicyRequired,
    PAM_GATEWAY_LIST_FAILED: PamErrorCode.GatewayListFailed,
    PAM_GATEWAY_CREATE_FAILED: PamErrorCode.GatewayCreateFailed,
    PAM_GATEWAY_NAME_REQUIRED: PamErrorCode.GatewayNameRequired,
    PAM_KSM_APP_REQUIRED: PamErrorCode.KsmAppRequired,
    PAM_KSM_APP_NOT_FOUND: PamErrorCode.KsmAppNotFound,
    PAM_MULTIPLE_KSM_APP_MATCHES: PamErrorCode.MultipleKsmAppMatches,
    PAM_INVALID_TOKEN_EXPIRY: PamErrorCode.InvalidTokenExpiry,
    PAM_CONFIG_INIT_FAILED: PamErrorCode.ConfigInitFailed,
    PAM_GATEWAY_REQUIRED: PamErrorCode.GatewayRequired,
    PAM_GATEWAY_NOT_FOUND: PamErrorCode.GatewayNotFound,
    PAM_GATEWAY_EDIT_NOTHING_TO_DO: PamErrorCode.GatewayEditNothingToDo,
    PAM_GATEWAY_EDIT_FAILED: PamErrorCode.GatewayEditFailed,
    PAM_GATEWAY_NODE_NOT_FOUND: PamErrorCode.GatewayNodeNotFound,
    PAM_MULTIPLE_GATEWAY_NODE_MATCHES: PamErrorCode.MultipleGatewayNodeMatches,
    PAM_GATEWAY_REMOVE_FAILED: PamErrorCode.GatewayRemoveFailed,
    PAM_GATEWAY_INVALID_MAX_INSTANCES: PamErrorCode.GatewayInvalidMaxInstances,
    PAM_GATEWAY_SET_MAX_INSTANCES_FAILED: PamErrorCode.GatewaySetMaxInstancesFailed,
    PAM_CONFIG_NOT_FOUND: PamErrorCode.ConfigNotFound,
    PAM_CONFIG_INVALID: PamErrorCode.ConfigInvalid,
    PAM_CONFIG_TITLE_REQUIRED: PamErrorCode.ConfigTitleRequired,
    PAM_CONFIG_TYPE_REQUIRED: PamErrorCode.ConfigTypeRequired,
    PAM_CONFIG_TYPE_INVALID: PamErrorCode.ConfigTypeInvalid,
    PAM_CONFIG_SHARED_FOLDER_REQUIRED: PamErrorCode.ConfigSharedFolderRequired,
    PAM_CONFIG_SHARED_FOLDER_NOT_FOUND: PamErrorCode.ConfigSharedFolderNotFound,
    PAM_CONFIG_CREATE_FAILED: PamErrorCode.ConfigCreateFailed,
    PAM_CONFIG_MOVE_FAILED: PamErrorCode.ConfigMoveFailed,
    PAM_CONFIG_REQUIRED: PamErrorCode.ConfigRequired,
    PAM_CONFIG_EDIT_NOTHING_TO_DO: PamErrorCode.ConfigEditNothingToDo,
    PAM_CONFIG_EDIT_FAILED: PamErrorCode.ConfigEditFailed,
    PAM_MULTIPLE_CONFIG_MATCHES: PamErrorCode.MultipleConfigMatches,
    PAM_CONFIG_REMOVE_FAILED: PamErrorCode.ConfigRemoveFailed,
} as const

export const KEEPER_PUBLIC_HOSTS: Record<string, string> = {
    US: 'keepersecurity.com',
    EU: 'keepersecurity.eu',
    AU: 'keepersecurity.com.au',
    CA: 'keepersecurity.ca',
    JP: 'keepersecurity.jp',
    GOV: 'govcloud.keepersecurity.us',
}
