name: Audit

on: [push]

jobs:
  audit:
    name: Audit Project

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Examples (node) - Installation
        run: npm i
        working-directory: ./examples/print-vault-node

      - name: Lib - Build
        run: yarn build
        working-directory: ./keeperapi

      - name: Examples (node) - Check Types
        run: npm run types:ci
        working-directory: ./examples/print-vault-node

      - name: Examples (browser) - Installation
        run: npm i
        working-directory: ./examples/print-vault-browser

      - name: Examples (browser) - Check Types
        run: npm run types:ci
        working-directory: ./examples/print-vault-browser

      - name: Lib - Check Types
        run: yarn types:ci
        working-directory: ./keeperapi

#      - name: Lib - Run Tests
#        run: npm run test:ci
#        working-directory: ./keeperapi
