name: Publish to NPM
on:
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    publish-npm:
        environment: prod
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./keeperapi

        steps:
            - name: Get the source code
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '24'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm install

            - name: Publish package
              run: npm publish
