name: Publish to NPM
permissions:
  contents: read
  pull-requests: write
on:
  workflow_dispatch:

jobs:
  publish-npm:
    environment: prod
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./keeperapi

    steps:
      - name: Get the source code
        uses: actions/checkout@v2

      - name: Retrieve secrets from KSM
        id: ksmsecrets
        uses: Keeper-Security/ksm-action@d92a3c5d1df69745083436ba189f64a9cc1b25f5
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          secrets: |
            NScQiZwrHJFCPv1gL8TX6Q/field/password > env:NPM_TOKEN

      - name: Install dependencies
        run: npm install

      - name: Publish package
        run: npm publish